# Generated by Django 2.2.9 on 2020-02-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiderDriver',
        ),
    ]
