# Generated by Django 2.2.9 on 2020-02-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_riderdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=120)),
                ('plateNumber', models.TextField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('MPV', 'MPV'), ('SUV', 'SUV'), ('Crossover', 'Crossover'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible')], default='Hatchback', max_length=100)),
                ('max_passenger_num', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('special_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
