# Generated by Django 2.2.9 on 2020-02-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='finish_time',
            field=models.DateTimeField(verbose_name='Finish Time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
