# Generated by Django 2.2.5 on 2020-02-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_riderdriver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.RemoveField(
            model_name='riderdriver',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='RiderDriver',
        ),
    ]
