# Generated by Django 2.2.5 on 2020-02-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200203_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdriver',
            name='is_driving',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
