# Generated by Django 2.2.5 on 2020-02-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_riderdriver_is_driving'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canShare',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
    ]
