# Generated by Django 2.2.5 on 2020-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200204_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridersharer',
            name='order',
        ),
        migrations.AddField(
            model_name='ridersharer',
            name='order',
            field=models.ManyToManyField(null=True, to='orders.Order'),
        ),
    ]
